from source_spider.spiders.middlewares.retry_middleware import OptionalRetryMiddleware
from source_spider.spiders.middlewares.ua_proxy import RandomUserAgent
from source_spider.spiders.middlewares.rountine_middleware import RoutineSpiderMiddleware
from source_spider.spiders.middlewares.selenium_middleware import SeleniumMiddleware